In [3]:
import numpy as np

In [5]:
a = np.arange(12,24)

In [25]:
b1 = np.ndarray((3,4), dtype = int , buffer = a)

In [27]:
b2 = np.reshape(a, (3,4))

In [30]:
b3 = np.reshape(a, (4,3))

In [32]:
b4 = np.reshape(a, (2, 6))

In [33]:
b5 = np.reshape(a, (6, 2))

In [35]:
c1 = np.reshape(a, (3, -1))

In [39]:
c2 = np.reshape(a, (2, -1))

In [41]:
c3 = np.reshape(a, (4, -1))

In [44]:
c4 = np.reshape(a, (6, -1))

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? нет, поскольку главный объект NumPy - это однородный многомерный массив.


#### пункт 2

In [7]:
d2 = np.random.randn(3000,4000)

In [10]:
d2.mean()

-0.4007394364525512

при увелчинее кол-ва элементов выборки, мы приближаем значение к нулю

In [11]:
d22 = a.flatten()

#### Пункт3

In [13]:
a = np.arange(20, 0, -2)

In [25]:
b1 = np.reshape((np.arange(20, 1, -2)), (1, 10))

Ну a это вектор, а b1 это двумерный


#### Пункт4

In [3]:
a = np.zeros((2, 2))

In [4]:
b = np.ones((3, 2))

In [6]:
v = np.vstack((a, b))

In [8]:
np.size(v)

10

#### Пункт5

In [13]:
a = np.arange(0,12)

In [14]:
A = a.reshape(4, 3)

In [15]:
At = A.transpose()

In [16]:
B = np.dot(A, At)
print(A.dot(At), '\n',B) #интересная запись 

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [17]:
np.linalg.det(B) 

0.0

Детерминат 0 а значит обратную матрицу построить невозможно

#### Пункт 6

In [28]:
np.random.seed(42)

In [20]:
c = np.random.randint(0, 16, 16)

In [21]:
c = c.reshape(4,4)

In [22]:
D = (c * 10) + B

In [23]:
np.linalg.det(D)

-76973199.9999999

In [24]:
np.linalg.matrix_rank(D)

4

In [25]:
Dinv = np.linalg.inv(D)

In [26]:
Dinv

array([[ 0.00336481,  0.0127117 , -0.02511679,  0.01767576],
       [-0.0010175 , -0.0220061 ,  0.00361061,  0.00606809],
       [ 0.00789418,  0.00668778,  0.00232445, -0.00606757],
       [-0.00759641,  0.00746416,  0.00468839, -0.00331804]])

#### Пункт 7

In [27]:
Dinv[(Dinv < 0)] = 0

In [28]:
Dinv[(Dinv > 0)] = 1

In [29]:
Dinv

array([[1., 1., 0., 1.],
       [0., 0., 1., 1.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.]])

In [30]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [31]:
c

array([[ 3,  7, 14,  1],
       [ 3,  1,  3,  1],
       [ 5, 14, 13,  8],
       [ 9, 14,  7,  1]])

In [34]:
E = np.where(Dinv, B, c)

In [35]:
E

array([[  5,  14,  14,  32],
       [  3,   1,  86, 122],
       [ 23,  86, 149,   8],
       [  9, 122, 212,   1]])